### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by benbuckman** [za-creature/coffeelint-taboo#1]
Running `coffeelint@1.16.0`, linting files that should definitely fail this rule, it passes with no errors shown.

### coffeelint.json

```json
"reject_identifiers": {
      "module": "coffeelint-taboo",
      "level": "error",
      "identifiers": ["debugger", "console", "console.trace", "it.only", "describe.only", "context.only"]
}
```

Does this module actually work for anyone?
Thanks

**Comment by za-creature** [comment]
Oh, wow, for some reason I didn't get notified about this

I guess a year and a half later is better than no reply, so here goes:

Thanks for reporting this, I'm unsure what went wrong on your end; it used to work for me around the end of 2016, but I haven't really used it since. I'm [not really into coffeescript anymore](https://github.com/za-creature/coffeescope/issues/43) so I'm afraid I can't be of any more help. Hope you found a viable alternative
